apiVersion: v1
kind: Template
metadata:
  name: simple-mysql
  annotations:
    description: Aplicacion SIMPLE con una base de datosMySQL
    iconClass: icon-php
    tags: instant-app,php,simple,mysql
  labels:
    template: simple-mysql
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
    name: simple-mysql
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: simple-mysql
- apiVersion: v1
  kind: Route
  metadata:
    name: simple-mysql
  spec:
    host: ${APPLICATION_DOMAIN}
    to:
      kind: Service
      name: simple-mysql
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: simple-mysql
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
    name: simple-mysql
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: simple-mysql:latest
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php-mcrypt:5.6
          namespace: openshift
      type: Source
    triggers:
    - type: ImageChange
    - type: ConfigChange
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
    name: simple-mysql
  spec:
    replicas: 1
    selector:
      name: simple-mysql
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: simple-mysql
        name: simple-mysql
      spec:
        containers:
        - env:
          - name: DATABASE_SERVICE_NAME
            value: ${DATABASE_SERVICE_NAME}
          - name: DATABASE_ENGINE
            value: ${DATABASE_ENGINE}
          - name: DATABASE_NAME
            value: ${DATABASE_NAME}
          - name: DATABASE_USER
            value: ${DATABASE_USER}
          - name: DATABASE_PASSWORD
            value: ${DATABASE_PASSWORD}
          - name: OPCACHE_REVALIDATE_FREQ
            value: ${OPCACHE_REVALIDATE_FREQ}
          - name: OPENSHIFT_TEMPLATE_NAME 
            value: simple-mysql 
          - name: APPLICATION_DOMAIN 
            value: ${APPLICATION_DOMAIN}
          - name: SIMPLE_DOMAIN 
            value: ${SIMPLE_DOMAIN}
          - name: SIMPLE_LOG_DIR 
            value: ${SIMPLE_LOG_DIR}
          - name: SIMPLE_SMTP_HOST 
            value: ${SIMPLE_SMTP_HOST}
          - name: SIMPLE_SMTP_USER
            value: ${SIMPLE_SMTP_USER}
          - name: SIMPLE_SMTP_PASSWORD
            value: ${SIMPLE_SMTP_PASSWORD}
          - name: SIMPLE_SMTP_PORT
            value: ${SIMPLE_SMTP_PORT}
          - name: SIMPLE_ENCRYPTION_KEY
            value: ${SIMPLE_ENCRYPTION_KEY}
          image: simple-mysql
          name: simple-mysql
          ports:
          - containerPort: 8080
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - simple-mysql
        from:
          kind: ImageStreamTag
          name: simple-mysql:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes the database server
    name: ${DATABASE_SERVICE_NAME}
  spec:
    ports:
    - name: mysql
      port: 3306
      targetPort: 3306
    selector:
      name: ${DATABASE_SERVICE_NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the database
    name: ${DATABASE_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${DATABASE_SERVICE_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${DATABASE_SERVICE_NAME}
        name: ${DATABASE_SERVICE_NAME}
      spec:
        containers:
        - env:
          - name: MYSQL_USER
            value: ${DATABASE_USER}
          - name: MYSQL_PASSWORD
            value: ${DATABASE_PASSWORD}
          - name: MYSQL_DATABASE
            value: ${DATABASE_NAME}
          image: mysql
          name: mysql
          ports:
          - containerPort: 3306
    triggers:
    - imageChangeParams:
        automatic: false
        containerNames:
        - mysql
        from:
          kind: ImageStreamTag
          name: mysql:5.6
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The URL of the repository with your application source code
  name: SOURCE_REPOSITORY_URL
  value: http://openshift:AVMteCrhZWrZS@gitlab.paas.agesic.red.uy/tramites-en-linea/simple.git
- description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch
  name: SOURCE_REPOSITORY_REF
  value: master
- description: Set this to the relative path to your project if it is not in the root
    of your repository
  name: CONTEXT_DIR
- description: The exposed hostname that will route to the CakePHP service, if left
    blank a value will be defaulted.
  name: APPLICATION_DOMAIN
- description: Log dir for SIMPLE app
  name: SIMPLE_LOG_DIR 
  value: /var/log/simple
- description: Default domain name for logins
  name: SIMPLE_DOMAIN
- description: SMTP Host for email notifications
  name: SIMPLE_SMTP_HOST
- description: SMTP Username for email notifications
  name: SIMPLE_SMTP_USER
- description: SMTP Password for email notifications
  name: SIMPLE_SMTP_PASSWORD
- description: SMTP Port for email notifications
  name: SIMPLE_SMTP_PORT
  value: '25'
- description: Encryption Key for SIMPLE data 
  from: '[a-zA-Z0-9]{20}'
  generate: expression
  name: SIMPLE_ENCRYPTION_KEY 
- description: A secret string used to configure the GitHub webhook
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: GITHUB_WEBHOOK_SECRET
- description: Database service name
  name: DATABASE_SERVICE_NAME
  value: mysql
- description: 'Database engine: postgresql, mysql or sqlite (default)'
  name: DATABASE_ENGINE
  value: mysql
- description: Database name
  name: DATABASE_NAME
  value: default
- description: Database user name
  name: DATABASE_USER
  value: simple
- description: Database user password
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: DATABASE_PASSWORD
- description: The How often to check script timestamps for updates, in seconds. 0
    will result in OPcache checking for updates on every request.
  name: OPCACHE_REVALIDATE_FREQ
  value: "2"

